"""Add enrollment_key to Subject model

Revision ID: 0161c9374304
Revises: 023117970bb4
Create Date: 2025-09-24 00:32:41.313832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0161c9374304'
down_revision = '023117970bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_key', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['enrollment_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('enrollment_key')

    # ### end Alembic commands ###
