"""add file_path to subject_content

Revision ID: 6fb9405dddcd
Revises: ffa71818d9d8
Create Date: 2026-01-19 21:40:35.582813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb9405dddcd'
down_revision = 'ffa71818d9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject_contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject_contents', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
