"""Add Assignment model

Revision ID: d20f1b24dd2b
Revises: 61ee7951fd40
Create Date: 2025-09-24 20:44:27.397771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd20f1b24dd2b'
down_revision = '61ee7951fd40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
        batch_op.alter_column('due_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('assignments_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['teacher_id'], ['id'])
        batch_op.create_foreign_key(None, 'subjects', ['subject_id'], ['id'])
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('assignments_ibfk_1'), 'courses', ['course_id'], ['id'])
        batch_op.alter_column('due_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
