"""Add form and code fields to Subject model

Revision ID: ffa71818d9d8
Revises: 9ce69c9ccdec
Create Date: 2026-01-19 00:01:13.974770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa71818d9d8'
down_revision = '9ce69c9ccdec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('code', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['code'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('form')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('code')
        batch_op.drop_column('form')

    # ### end Alembic commands ###
